model_name: HuggingFaceTB/SmolLM-135M
device: cuda
dtype: float32
max_new_tokens: 64
max_length: 64
temperature: 0.2
top_p: 1.0
truncation: true
requires_auth: false
trust_remote_code: false
save_activations: true
act_dir: cache/smollm_activations/135m
