model_name: gpt2-large
device: cuda
dtype: float32
max_new_tokens: 64
temperature: 0.2
top_p: 1.0
requires_auth: false
trust_remote_code: false
save_activations: true
act_dir: cache/smollm_activations/1.7b
