model_name: meta-llama/Llama-3.2-1B
device: cpu
dtype: float32
max_new_tokens: 32  # Reduced for CPU safety
temperature: 0.0
top_p: 1.0
seed: 1337
save_activations: true
act_dir: cache/activations
trust_remote_code: true
requires_auth: true
batch_size: 1  # CPU-safe batch size
